version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "quarterly"
      time: "08:00"
      timezone: Asia/Shanghai
    labels:
      - "skip-changelog"
      - "dependencies"
    rebase-strategy: disabled

  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: "quarterly"
      time: "08:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 10
    labels:
      - skip-changelog
      - dependencies
    rebase-strategy: disabled
